apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners-stream-ci
spec:
  replicas: replicas-placeholder
  template:
    spec:
      repository: spring-cloud/stream-applications
#      image: 'summerwind/actions-runner-dind:tag-placeholder'
      dockerdWithinRunnerContainer: true
      priorityClassName: high-priority
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: stream-metadata-default
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      resources:
        requests:
          cpu: "1500m"
          memory: "1536Mi"
      env:
        - name: STARTUP_DELAY_IN_SECONDS
          value: "10"
        - name: DISABLE_WAIT_FOR_DOCKER
          value: "true"
      labels:
        - stream-ci
