name: 'CI - 2021.0.x'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      TMC_API_TOKEN: ${{ secrets.TMC_API_TOKEN }}
      GCP_CRED_JSON: ${{ secrets.GCP_CRED_JSON }}
      CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
    with:
      version: '2021.0.x'
      branch: '2021.0.x'
