name: 'CI - 2021.1.x'

on:
  workflow_dispatch:
    inputs:
      verbose:
        required: false
        default: 'false'
        description: 'Produces verbose output'
jobs:
  build:
    uses: ./.github/workflows/common.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      TMC_API_TOKEN: ${{ secrets.TMC_API_TOKEN }}
      GCP_CRED_JSON: ${{ secrets.GCP_CRED_JSON }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    with:
      branch: '2021.1.x'
      verbose: ${{ inputs.verbose == 'true' }}
