name: 'CI - 2021.1.x'

on:
  workflow_dispatch:
    inputs:
      verbose:
        required: false
        default: 'false'
        description: 'Produces verbose output'
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - '2021.1.x'
jobs:
  build:
    uses: ./.github/workflows/common.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      TMC_API_TOKEN: ${{ secrets.TMC_API_TOKEN }}
      GCP_CRED_JSON: ${{ secrets.GCP_CRED_JSON }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    with:
      branch: '2021.1.x'
      verbose: ${{ inputs.verbose == 'true' }}
